services:
  pdf-unlock:
    build:
      context: .
      dockerfile: Dockerfile
    image: potaesm/hashcat-pdf-unlocker:latest
    working_dir: /data
    gpus: all
    environment:
      INPUT_DIR: /data/input
      OUTPUT_DIR: /data/output
      POTFILE_PATH: /work/hashcat.potfile
      HASHCAT_DIRECT_MASK: "true"
      HASHCAT_STATUS_TIMER: "10"
      OUTPUT_SUFFIX: ""
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    volumes:
      - ./input:/data/input
      - ./output:/data/output
      - ./work:/work
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [compute, utility]
